export const Routes = {
  HOME: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password',
  CATEGORIES: '/categories',
  TEAM: '/team',
  TEAM_ADD: '/team/add',
  SUPPORT: '/support',
  SUPPORT_ALLOW_IMPERSONATE: '/support/allow-impersonate',
  SUPPORT_CONTACT_US: '/support/contact-us',
  SUPPORT_TICKETS: '/support/tickets',
  SUPPORT_SCHEDULE_CALL: '/support/schedule-call',
  PROMOTION: '/promotions',
  PLACE_AN_ORDER: '/place-an-order',
  COMPANY_INFORMATION: '/company-info',
  ORDERS: '/orders',
  INVOICES: '/invoices',
  STATEMENTS: './statements',
  PROMOTIONS: './promotions',
  CERTIFICATE_GENERATION: '/certificate-generation',
};
